# Generated by Django 4.2.1 on 2023-05-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
